# Data
path: ./hand_keypoint_dataset_26k
train: images/train 
val: images/val 

# Keypoints
kpt_shape: [21, 3]  
flip_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

# Classes
names:
  0: hand